import { HttpResponseModel } from "@odata2ts/http-client-api";
import { FetchClient } from "@odata2ts/http-client-fetch";
import { ODataCollectionResponseV2, ODataEntityModelResponseV2 } from "@odata2ts/odata-core";
import { ODataConcurrencyError } from "@odata2ts/odata-service";
import { describe, expect, expectTypeOf, test } from "vitest";
import { Book, EditableBook, LibraryService } from "../../src-generated/library/index.js";
import { expectODataError } from "../expectODataError.js";
import { BASE_URL, BOOK_DER_PROZESS, COPY_KEY, LIBRARY, UNKNOWN_ID } from "../LibraryTestConstants.js";

/**
 * The plain CRUD surface against a native OData V2 server.
 *
 * Worth reading next to `int-test/cap/test/v2`, which drives the same client against a V2 *adapter* in
 * front of a V4 service. Several things this file asserts are where the two disagree - most visibly the
 * write responses, which Olingo gets right and the adapter does not.
 */
describe("Olingo Library: CRUD operations", () => {
  test("a key is written with its type", () => {
    expect(LIBRARY.Books(BOOK_DER_PROZESS).getPath()).toBe(`${BASE_URL}/Books(guid'${BOOK_DER_PROZESS}')`);
    expect(LIBRARY.Copies(COPY_KEY).getPath()).toBe(
      `${BASE_URL}/Copies(MediumId=guid'${BOOK_DER_PROZESS}',InventoryNumber=1001)`,
    );
  });

  test("read entity by key", async () => {
    const result = await LIBRARY.Books(BOOK_DER_PROZESS).query().execute();

    expect(result.status).toBe(200);
    expect(result.data.d).toMatchObject({
      Id: BOOK_DER_PROZESS,
      Title: "Der Prozess",
      ISBN: "9783150094440",
      PageCount: 224,
    });
    expect(result.data.d.__metadata.uri).toBe(`${BASE_URL}/Books(guid'${BOOK_DER_PROZESS}')`);

    expectTypeOf(result).toEqualTypeOf<HttpResponseModel<ODataEntityModelResponseV2<Book>>>();
    expectTypeOf(result.data.d.Title).toEqualTypeOf<string>();
    expectTypeOf(result.data.d.PageCount).toEqualTypeOf<number | null>();
  });

  test("read entity collection", async () => {
    const result = await LIBRARY.Books().query().execute();

    expect(result.status).toBe(200);
    expect(result.data.d.results.length).toBeGreaterThan(0);
    expect(result.data.d.results.map((book) => book.Title)).toContain("Der Prozess");

    expectTypeOf(result).toEqualTypeOf<HttpResponseModel<ODataCollectionResponseV2<Book>>>();
  });

  test("an unexpanded navigation property arrives as a deferred link", async () => {
    const result = await LIBRARY.Books(BOOK_DER_PROZESS).query().execute();

    expect(result.data.d.Copies).toStrictEqual({
      __deferred: { uri: `${BASE_URL}/Books(guid'${BOOK_DER_PROZESS}')/Copies` },
    });
  });

  test("read with unknown key yields 404", async () => {
    await expectODataError(LIBRARY.Books(UNKNOWN_ID).query().execute(), {
      status: 404,
      message: /could not be found/,
    });
  });

  test("create, read, update, patch and delete an entity", async () => {
    const newBook: EditableBook = { Title: "Das Schloss", Language: "de", PageCount: 352 };

    const created = await LIBRARY.Books().create(newBook).execute();
    expect(created.status).toBe(201);
    expect(created.data.d).toMatchObject(newBook);
    expectTypeOf(created).toEqualTypeOf<HttpResponseModel<ODataEntityModelResponseV2<Book>>>();

    // the key is generated by the server, so a client need not invent one
    const id = created.data.d.Id;
    expect(id).toBeDefined();

    const read = await LIBRARY.Books(id).query().execute();
    expect(read.status).toBe(200);
    expect(read.data.d).toMatchObject(newBook);

    /*
     * Both write verbs answer 204 with no body - exactly what V2 prescribes, and exactly what odata2ts
     * types them as. The CAP V2 adapter answers 200 with the full entity here, which the V2 client has
     * no way to express; see int-test/cap/test/v2/core/CrudOperations.test.ts.
     */
    const updated = await LIBRARY.Books(id)
      .update({ Title: "Das Schloss (2. Auflage)", Language: "de", PageCount: 353 })
      .execute();
    expect(updated.status).toBe(204);
    expectTypeOf(updated).toEqualTypeOf<HttpResponseModel<undefined>>();
    expect((await LIBRARY.Books(id).query().execute()).data.d.PageCount).toBe(353);

    // patch is a MERGE here: V2 has no PATCH verb, so odata2ts tunnels it through POST + X-Http-Method
    const patched = await LIBRARY.Books(id).patch({ PageCount: 354 }).execute();
    expect([200, 204]).toContain(patched.status);

    const afterPatch = await LIBRARY.Books(id).query().execute();
    expect(afterPatch.data.d.PageCount).toBe(354);
    // untouched properties survive a merge
    expect(afterPatch.data.d.Title).toBe("Das Schloss (2. Auflage)");

    const deleted = await LIBRARY.Books(id).delete().execute();
    expect([200, 204]).toContain(deleted.status);

    await expectODataError(LIBRARY.Books(id).query().execute(), { status: 404, message: /could not be found/ });
  });

  test("deleting an unknown entity yields 404", async () => {
    await expectODataError(LIBRARY.Books(UNKNOWN_ID).delete().execute(), {
      status: 404,
      message: /could not be found/,
    });
  });

  test("a deep insert creates the nested entities and links them", async () => {
    // Olingo's ListsProcessor runs a create payload through `createInlinedEntities`, which creates each
    // nested entity and then links it - so the foreign key the client sent is overwritten with the key
    // of the parent that did not exist yet when the payload was written.
    const created = await LIBRARY.Books()
      .create({
        Title: "Deep Insert Book",
        Language: "de",
        Copies: { results: [{ MediumId: UNKNOWN_ID, InventoryNumber: 9901, IsLoanable: true }] },
      } as EditableBook)
      .execute();

    expect(created.status).toBe(201);

    const copies = await LIBRARY.Books(created.data.d.Id).Copies().query().execute();
    expect(copies.data.d.results.map((copy) => [copy.MediumId, copy.InventoryNumber])).toStrictEqual([
      [created.data.d.Id, 9901],
    ]);

    await LIBRARY.Books(created.data.d.Id).delete().execute();
  });

  test("an entity with a concurrency token round-trips", async () => {
    /*
     * `Copy.Condition` is `ConcurrencyMode="Fixed"`, so every copy carries an ETag and Olingo refuses a
     * write without `If-Match`. This used to be the end of the story - odata2ts read no `__metadata.etag`
     * and sent no header, so `Copies` was read-only through the generated client. The V2 concurrency
     * facet is now normalized into `Core.OptimisticConcurrency`, so the client does both.
     */
    const copy = await LIBRARY.Copies(COPY_KEY).query().execute();
    expect(copy.data.d.__metadata.etag).toMatch(/^W\//);

    // the read filled the ETag store, so the write carries `If-Match` without being told
    const patched = await LIBRARY.Copies(COPY_KEY).patch({ IsLoanable: false }).execute();
    expect([200, 204]).toContain(patched.status);
  });

  test("a stale concurrency token is refused", async () => {
    // this server compares the token, unlike Olingo itself - see its FEATURE-COVERAGE.md §3.1
    await LIBRARY.Copies(COPY_KEY).query().execute();

    await expectODataError(LIBRARY.Copies(COPY_KEY).patch({ IsLoanable: true }).withETag('W/"stale"').execute(), {
      status: 412,
      message: /.*/,
    });
  });

  test("writing without reading first is refused before a request is sent", async () => {
    const untouched = new LibraryService(new FetchClient(), BASE_URL);

    await expect(untouched.Copies(COPY_KEY).patch({ IsLoanable: true }).execute()).rejects.toThrow(
      ODataConcurrencyError,
    );
  });

  test("a navigation property is addressable as a sub-resource", async () => {
    const toMany = await LIBRARY.Books(BOOK_DER_PROZESS).Copies().query().execute();
    expect(toMany.status).toBe(200);
    expect(toMany.data.d.results.every((copy) => copy.MediumId === BOOK_DER_PROZESS)).toBe(true);

    const toOne = await LIBRARY.Books(BOOK_DER_PROZESS).Publisher().query().execute();
    expect(toOne.status).toBe(200);
    expect(toOne.data.d.Name).toBe("Reclam");
  });
});
