export enum QueryObjectTypes {
  QEnumCollection = "QEnumCollection",
  QNumericEnumCollection = "QNumericEnumCollection",
  QEnumPath = "QEnumPath",
  QFlagsEnumPath = "QFlagsEnumPath",
  QEnumCollectionPath = "QEnumCollectionPath",
  QNumericEnumPath = "QNumericEnumPath",
  QNumericFlagsEnumPath = "QNumericFlagsEnumPath",
  QNumericEnumCollectionPath = "QNumericEnumCollectionPath",
  QCollectionPath = "QCollectionPath",
  QComplexPath = "QComplexPath",
  QFlatComplexPath = "QFlatComplexPath",
  QEntityPath = "QEntityPath",
  QComplexCollectionPath = "QComplexCollectionPath",
  QEntityCollectionPath = "QEntityCollectionPath",
}
