import { describe, expect, test } from "vitest";
import { EditableBooks } from "../../src-generated/library/LibraryModel";
import { BOOK_DER_PROZESS, LIBRARY, UNKNOWN_ID } from "../LibraryTestConstants";

/**
 * The plain CRUD surface. Reading here means reading *without* any system query option - those are
 * covered by QueryFunctionality.test.ts.
 */
describe("CAP Library: CRUD operations", () => {
  test("read entity by key", async () => {
    const result = await LIBRARY.Books(BOOK_DER_PROZESS).query().execute();

    expect(result.status).toBe(200);
    expect(result.data).toMatchObject({
      Id: BOOK_DER_PROZESS,
      Title: "Der Prozess",
      Language: "de",
      ISBN: "9783150094440",
      PageCount: 224,
    });
  });

  test("read entity collection", async () => {
    const result = await LIBRARY.Books().query().execute();

    expect(result.status).toBe(200);
    expect(result.data.value.length).toBeGreaterThan(0);
    expect(result.data.value.map((book) => book.Title)).toContain("Der Prozess");
  });

  test("read with unknown key yields 404", async () => {
    await expect(LIBRARY.Books(UNKNOWN_ID).query().execute()).rejects.toMatchObject({ status: 404 });
  });

  test("create, read, patch and delete an entity", async () => {
    const newBook: EditableBooks = {
      Title: "Das Schloss",
      Language: "de",
      PageCount: 352,
    };

    // create
    const created = await LIBRARY.Books().create(newBook).execute();
    expect(created.status).toBe(201);
    expect(created.data).toMatchObject(newBook);

    // the key is generated by the server
    const id = created.data.Id;
    expect(id).toBeDefined();

    // read it back
    const read = await LIBRARY.Books(id).query().execute();
    expect(read.status).toBe(200);
    expect(read.data).toMatchObject(newBook);

    // patch a single property
    await LIBRARY.Books(id).patch({ PageCount: 353 }).execute();
    const patched = await LIBRARY.Books(id).query().execute();
    expect(patched.data.PageCount).toBe(353);
    // untouched properties survive a patch
    expect(patched.data.Title).toBe(newBook.Title);

    // delete
    const deleted = await LIBRARY.Books(id).delete().execute();
    expect(deleted.status).toBe(204);

    // and it is gone
    await expect(LIBRARY.Books(id).query().execute()).rejects.toMatchObject({ status: 404 });
  });
});
