import { ODataCollectionResponseV4, ODataModelResponseV4 } from "@odata2ts/odata-core";
import { ODataResponseModel } from "@odata2ts/odata-service";
import { describe, expect, expectTypeOf, test } from "vitest";
import { Books, EditableBooks } from "../../src-generated/library/LibraryModel.js";
import { expectODataError } from "../expectODataError.js";
import { BOOK_DER_PROZESS, LIBRARY, UNKNOWN_ID } from "../LibraryTestConstants.js";

/**
 * The plain CRUD surface. Reading here means reading *without* any system query option - those are
 * covered by QueryFunctionality.test.ts.
 */
describe("CAP Library: CRUD operations", () => {
  test("read entity by key", async () => {
    const result = await LIBRARY.Books(BOOK_DER_PROZESS).query().execute();

    expect(result.status).toBe(200);
    expect(result.data).toMatchObject({
      Id: BOOK_DER_PROZESS,
      Title: "Der Prozess",
      Language: "de",
      ISBN: "9783150094440",
      PageCount: 224,
    });

    // a single entity arrives unwrapped, and the nullability comes from the metadata
    expectTypeOf(result).toEqualTypeOf<ODataResponseModel<ODataModelResponseV4<Books>>>();
    expectTypeOf(result.data.Title).toEqualTypeOf<string>();
    expectTypeOf(result.data.PageCount).toEqualTypeOf<number | null>();
  });

  test("read entity collection", async () => {
    const result = await LIBRARY.Books().query().execute();

    expect(result.status).toBe(200);
    expect(result.data.value.length).toBeGreaterThan(0);
    expect(result.data.value.map((book) => book.Title)).toContain("Der Prozess");

    // a collection is wrapped in `value` - the difference to the single entity above
    expectTypeOf(result).toEqualTypeOf<ODataResponseModel<ODataCollectionResponseV4<Books>>>();
    expectTypeOf(result.data.value).toEqualTypeOf<Array<Books>>();
  });

  test("read with unknown key yields 404", async () => {
    // CAP does send an error body, so a real message reaches the client - unlike ASP.NET, which sends
    // none and leaves the client's fallback text showing.
    await expectODataError(LIBRARY.Books(UNKNOWN_ID).query().execute(), { status: 404, message: /Not Found/ });
  });

  test("create, read, patch and delete an entity", async () => {
    const newBook: EditableBooks = {
      Title: "Das Schloss",
      Language: "de",
      PageCount: 352,
    };

    // create
    const created = await LIBRARY.Books().create(newBook).execute();
    expect(created.status).toBe(201);
    expect(created.data).toMatchObject(newBook);
    expectTypeOf(created).toEqualTypeOf<ODataResponseModel<ODataModelResponseV4<Books>>>();

    // the key is generated by the server
    const id = created.data.Id;
    expect(id).toBeDefined();

    // read it back
    const read = await LIBRARY.Books(id).query().execute();
    expect(read.status).toBe(200);
    expect(read.data).toMatchObject(newBook);

    // patch a single property
    await LIBRARY.Books(id).patch({ PageCount: 353 }).execute();
    const patched = await LIBRARY.Books(id).query().execute();
    expect(patched.data.PageCount).toBe(353);
    // untouched properties survive a patch
    expect(patched.data.Title).toBe(newBook.Title);

    // delete
    const deleted = await LIBRARY.Books(id).delete().execute();
    expect(deleted.status).toBe(204);
    expectTypeOf(deleted).toEqualTypeOf<ODataResponseModel<undefined>>();

    // and it is gone
    await expectODataError(LIBRARY.Books(id).query().execute(), { status: 404, message: /Not Found/ });
  });

  test("deleting an unknown entity yields 404", async () => {
    await expectODataError(LIBRARY.Books(UNKNOWN_ID).delete().execute(), { status: 404, message: /Not Found/ });
  });

  test("patch answers with the entity by default here", async () => {
    // Where ASP.NET needs `Prefer: return=representation` to send a body, CAP sends one anyway - so the
    // `<true>` typing matches this server without the header. Pinned because a test written against CAP
    // alone would suggest odata2ts sends that header, which it never does.
    const created = await LIBRARY.Books().create({ Title: "Prefer Probe", Language: "de" }).execute();

    const patched = await LIBRARY.Books(created.data.Id).patch<true>({ PageCount: 42 }).execute();

    expect(patched.status).toBe(200);
    expect(patched.data.PageCount).toBe(42);
    expectTypeOf(patched).toEqualTypeOf<ODataResponseModel<ODataModelResponseV4<Books>>>();

    await LIBRARY.Books(created.data.Id).delete().execute();
  });
});
