import {
  CacheKeyMode,
  ConfigFileOptions,
  EmitModes,
  KeyProperties,
  ManagedPropertyMode,
  Modes,
  TypeModel,
} from "@odata2ts/odata2ts";

/** The running server to refresh from, or `undefined` to read the committed snapshot - see below. */
const SOURCE_URL = process.env.LIBRARY_BASE_URL;
const SOURCE = "resource/library.xml";

/**
 * Generates the odata2ts client for the standardized "Library" OData V4 test model, as served by the
 * ASP.NET Core implementation (repo `odata2ts/test-server-asp-net`).
 *
 * The source is a committed snapshot of the server's actual `$metadata` (`resource/library.xml`) -
 * odata2ts is tested against the metadata ASP.NET Core OData really emits, not against the idealized
 * reference model. Notably that metadata has no `TypeDefinition` and no `SRID` facets, neither of which
 * the model builder can express; see FEATURE-COVERAGE.md in the server repo. `Partner` *is* declared on
 * both sides of every relationship (6 attributes) - which is what puts grade A and grade B navigation
 * properties into this client's `cacheKeys` derivation, see the `library` service below.
 *
 * The snapshot refreshes itself from a running server: point `LIBRARY_BASE_URL` at one and the first
 * service downloads `$metadata` and overwrites the file, which the services after it then read, so a
 * model change never has to be copied in by hand. It is the same variable the test setup takes an externally started server from:
 *
 * ```
 * LIBRARY_BASE_URL=http://localhost:4004/odata/v4/library yarn build
 * ```
 *
 * Unset - which is how CI runs, where the container only comes up for the test run and `yarn build`
 * happens before it - the committed snapshot is used as-is and generation stays offline.
 *
 * The binding notations are the point of this package: this server is the first one we have that actually
 * honours them, so they are proven out end to end here. They are generated by default nowadays, which is
 * why no option says so.
 *
 * `bundledFileGeneration` is off - the default since the file layout became the user's choice - as half of
 * a division of labour: `int-test/cap` pins the bundled form, so both layouts are exercised at runtime
 * rather than only type-checked.
 *
 * The model is generated a second time, with `allowRenaming` on - see the `libraryRenamed` service below.
 */
const config: ConfigFileOptions = {
  mode: Modes.service,
  emitMode: EmitModes.ts,
  // also pretty-prints the downloaded metadata before it is stored
  prettier: true,
  debug: true,
  // spelled out although it is the default, because it is half of a division of labour: this package
  // generates a folder per model, `int-test/cap` pins the bundled form, so both layouts meet a real server
  bundledFileGeneration: false,
  // on, because the property services are a generator feature of their own and otherwise never
  // meet a real server: see test/feature/PropertyServices.test.ts
  enablePrimitivePropertyServices: true,
  services: {
    library: {
      serviceName: "Library",
      // the one service that refreshes the snapshot; the others below read the file it leaves behind,
      // so this entry has to stay first
      sourceUrl: SOURCE_URL,
      source: SOURCE,
      refreshFile: true,
      output: "src-generated/library",
      // typeFlattening rather than hierarchical, and here rather than anywhere else: this metadata
      // reproduces the reference model exactly, which puts all four hop outcomes into one client - grade A
      // to-many and to-one, grade B, grade C and containment. So this is the one package that can show
      // grade C and containment staying hierarchical *inside* a flattened client, and it is where the
      // convergence claim is held against a real server.
      cacheKeys: { mode: CacheKeyMode.typeFlattening },
    },
    /**
     * The same model once more, targeting OData 4.01 instead of the default 4.0.
     *
     * Not distributed across the two V4 packages the way `enableNativeInOperator` is, because it cannot be:
     * CAP does not speak 4.01, so this server is the only place the option can be held against anything.
     * Hence additive, next to the 4.0 client rather than instead of it - which is what the version
     * difference needs anyway, since the whole point is that the two spell the same request differently.
     *
     * What changes: a binding loses its own property name and shares one with a deep insert
     * (`{"@id": key}` instead of `Nav@odata.bind`), the control information in a response drops the
     * `odata.` prefix (`@count` rather than `@odata.count`), and requests carrying a body announce
     * `OData-Version: 4.01`. All three are payload, so none of them is visible to a type check.
     * See test/feature/ODataVersion401.test.ts.
     */
    library401: {
      serviceName: "Library401",
      source: SOURCE,
      output: "src-generated/library-401",
      v4: { odataVersion: "4.01" },
    },
    /**
     * The same model a second time, with renaming switched on.
     *
     * Generated separately rather than replacing the raw client, because the point is the *mapping* between
     * the two name forms, and a mapping is only observable where both ends are visible. With a single,
     * renamed client a wrongly built URL and a broken name mapping look exactly alike; next to a client
     * whose names are the server's own, they do not.
     *
     * `allowRenaming` is a generator feature which nevertheless has to hold on the wire: it renames what the
     * caller writes, never what is sent. Every `$select`, `$filter` and `$orderby`, every key predicate and
     * every payload has to carry the OData name again, and the response has to be read back into the renamed
     * property. Only a server rejects the wrong spelling - a fixture test accepts a broken mapping just as
     * happily as a correct one. See test/feature/Renaming.test.ts.
     */
    libraryRenamed: {
      serviceName: "LibraryRenamed",
      source: SOURCE,
      output: "src-generated/library-renamed",
      allowRenaming: true,
      // `Location_` (the shelf mark) and `Location` (the branch an item sits in) are distinct OData names,
      // but camelCase collapses both onto `location`. The generator refuses to emit that, so one of them
      // has to be told apart by hand - which is what this option is for.
      propertiesByName: [{ name: "Location_", mappedName: "shelfLocation" }],
      // The model carries `Branch` twice, in two namespaces. Unbundled generation keeps both - they live in
      // folders of their own and the barrels re-export each namespace under its own name - but two types
      // called `Branch` are a trap for the reader. Bundled generation would have invented `Branch2` here;
      // this says what it actually is.
      byTypeAndName: [
        {
          name: "PublisherRegistry.Branch",
          type: TypeModel.EntityType,
          mappedName: "PublisherBranch",
        },
      ],
    },
    /**
     * The same model once more under `managedPropertyMode: "strictOmit"`, where an immutable property is
     * dropped from an update payload instead of merely being optional in it.
     *
     * Generated separately rather than replacing the raw client, as with the renamed one above: the
     * default (`lenient`) shape is what most users get and is worth pinning in its own right, and the two
     * modes only mean anything held against each other - the same property is optional in one client's
     * write model and absent from the other's.
     *
     * A server is what settles this, because the mode is an assertion about the *server's* behaviour: that
     * `Loan.LoanedAt`, which `Core.Immutable` marks, is genuinely fixed after creation, and that leaving
     * it out of a PUT is therefore not a loss of data. See test/feature/ImmutableProperties.test.ts.
     */
    libraryStrict: {
      serviceName: "LibraryStrict",
      source: SOURCE,
      output: "src-generated/library-strict",
      managedPropertyMode: ManagedPropertyMode.strictOmit,
      // The servers now declare every generated key, so a key left bare really is the client's - which
      // is what makes `strict` safe here and pointless anywhere else: it demands a non-nullable key on
      // create, and after this release only `Branch` and `Copy` still are one.
      keyProperties: KeyProperties.strict,
    },
  },
};

export default config;
