###
# Name: Northwind
# Type: V2 - Read Only
# Address: https://services.odata.org/V2/Northwind/Northwind.svc
###

# --- METADATA ---
### @name metadata
GET {{rootUrl}}/$metadata

### Get Version
GET {{rootUrl}}

# --- Queries ---
### @name list categories
GET {{rootUrl}}/Categories?$inlinecount=allpages
Accept: {{contentType}}

### @name get one category
GET {{rootUrl}}/Categories(1)
Accept: {{contentType}}

### @name list products
GET {{rootUrl}}/Products?$inlinecount=allpages
Accept: {{contentType}}

### @name get product zero
GET {{rootUrl}}/Products(4)
Accept: {{contentType}}

### @name get unknown product
GET {{rootUrl}}/Products(666)
Accept: {{contentType}}

### @name get primitive property
GET {{rootUrl}}/Products(4)/ProductName
Accept: {{contentType}}

### @name get primitive null value
GET {{rootUrl}}/Orders(10248)/ShipRegion
Accept: {{contentType}}

### @name get raw primitive property
GET {{rootUrl}}/Products(4)/ProductName/$value

### @name get raw primitive null value => 404?!
GET {{rootUrl}}/Orders(10248)/ShipRegion/$value

### @name expanding
GET {{rootUrl}}/Products(4)?$expand=Category
Accept: {{contentType}}

### @name expanding collection
GET {{rootUrl}}/Products(4)?$select=Order_Details&$expand=Order_Details
Accept: {{contentType}}

### @name deep expanding
GET {{rootUrl}}/Products(0)?$expand=Category/Products
Accept: {{contentType}}

### @name selecting nested
GET {{rootUrl}}/Products?$select=ID,Name,Category/ID&$expand=Category
Accept: {{contentType}}

### @name selecting nested without expand => fails 400
GET {{rootUrl}}/Products?$select=ProductID,ProductName,Category/CategoryID
Accept: {{contentType}}

### @name selecting deeply nested
GET {{rootUrl}}/Products(4)?$select=ProductID,ProductName,Category/CategoryID,Category/Products/ProductName&$expand=Category/Products
Accept: {{contentType}}

### @name selecting deeply nested with individual expands
GET {{rootUrl}}/Products(4)?$select=ProductID,ProductName,Category/CategoryID,Category/Products/ProductName&$expand=Category,Category/Products
Accept: {{contentType}}

### @name filter boolean by ge
GET {{rootUrl}}/Products?$inlinecount=allpages&$filter=Discontinued gt null
Accept: {{contentType}}

### @name filter by price (decimal)
GET {{rootUrl}}/Products?$inlinecount=allpages&$filter=UnitPrice ge 21.2m
Accept: {{contentType}}
