# --- METADATA ---
### @name metadata
GET {{rootUrl}}/$metadata

### Get Version
GET {{rootUrl}}


# --- Queries ---
### @name list products
GET {{rootUrl}}/Products?$inlinecount=allpages
Accept: {{contentType}}

### @name filter by price (decimal)
GET {{rootUrl}}/Products?$inlinecount=allpages&$filter=UnitPrice ge 21.2m
Accept: {{contentType}}

### @name get product zero
GET {{rootUrl}}/Products(4)
Accept: {{contentType}}

### @name get unknown product
GET {{rootUrl}}/Products(666)
Accept: {{contentType}}

### @name expanding
GET {{rootUrl}}/Products(4)?$expand=Category
Accept: {{contentType}}

### @name deep expanding
GET {{rootUrl}}/Products(0)?$expand=Category/Products
Accept: {{contentType}}

### @name selecting nested
GET {{rootUrl}}/Products?$select=ID,Name,Category/ID&$expand=Category
Accept: {{contentType}}

### @name selecting nested without expand => fails 400
GET {{rootUrl}}/Products?$select=ProductID,ProductName,Category/CategoryID
Accept: {{contentType}}

### @name selecting deeply nested
GET {{rootUrl}}/Products(4)?$select=ProductID,ProductName,Category/CategoryID,Category/Products/ProductName&$expand=Category/Products
Accept: {{contentType}}

### @name selecting deeply nested with individual expands
GET {{rootUrl}}/Products(4)?$select=ProductID,ProductName,Category/CategoryID,Category/Products/ProductName&$expand=Category,Category/Products
Accept: {{contentType}}

### @name filter boolean by ge
GET {{rootUrl}}/Products?$inlinecount=allpages&$filter=Discontinued gt null
Accept: {{contentType}}


# --- Create Entity ---
### @name create new product
POST {{rootUrl}}/Products
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "ID": 999,
  "Description": "Test Description",
  "Name": "TestName",
  "Price": "12.88",
  "Rating": 1,
  "ReleaseDate": "2022-01-01T00:00:00"
}

### PATCH doesn't work and merge is not supported by HTTPClient
### @name update new product
PATCH {{rootUrl}}/Products(999)
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "Description": "Test Descriptioning!!!",
  "Rating": 3
}

### @name update category association
PATCH {{rootUrl}}/Products(999)
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "Category": { uri: "{{rootUrl}}/Categories(1)" }
}


### @name delete new product
DELETE {{rootUrl}}/Products(999)
Accept: {{contentType}}

# --- Create Entity With Association ---
### @name create new product with association
POST {{rootUrl}}/Products
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "ID": 999,
  "Description": "Test Description",
  "Name": "TestName",
  "Price": "12.88",
  "Rating": 1,
  "ReleaseDate": "2022-01-01T00:00:00",
  "Category": { ID: 1 }
}
}
