###
# Name: OData
# Type: V2 - Read / Write
# Address: https://services.odata.org/V2/Northwind/Northwind.svc
###

# --- METADATA ---
###
# @name metadata
GET {{baseUrl}}/$metadata

### Get Version
GET {{rootUrl}}


# --- Data Types
###
# @name DateTime
GET {{baseUrl}}/Products?$inlinecount=allpages&$select=ReleaseDate
Accept: {{contentType}}
###
# @name ComplexType
GET {{baseUrl}}/Suppliers(0)/Address
Accept: {{contentType}}
###
# @name Single Value
GET {{baseUrl}}/Suppliers(0)/Name
Accept: {{contentType}}
###
# @name Raw Value
GET {{baseUrl}}/Suppliers(0)/Name/$value


#--- Functions ---
###
# @name Function
GET {{baseUrl}}/GetProductsByRating?rating=3
Accept: {{contentType}}


# --- Queries ---
###
# @name list products
GET {{baseUrl}}/Products?$inlinecount=allpages
Accept: {{contentType}}

###
# @name get complex property
GET {{baseUrl}}/Suppliers(0)/Address
Accept: {{contentType}}

###
# @name get product zero
GET {{baseUrl}}/Products(0)
Accept: {{contentType}}

###
# @name get unknown product
GET {{baseUrl}}/Products(666)
Accept: {{contentType}}

###
# @name get primitive property
GET {{baseUrl}}/Products(0)/Description
Accept: {{contentType}}

###
# @name get primitive property with null value
GET {{baseUrl}}/Products(0)/DiscontinuedDate
Accept: {{contentType}}

###
# @name get primitive property raw value
GET {{baseUrl}}/Products(0)/Description/$value

###
# @name get primitive property raw null value => 404
GET {{baseUrl}}/Products(0)/DiscontinuedDate/$value

###
# @name expanding
GET {{baseUrl}}/Products?$expand=Category
Accept: {{contentType}}

###
# @name deep expanding
GET {{baseUrl}}/Products(0)?$expand=Category/Products
Accept: {{contentType}}

###
# @name selecting nested
GET {{baseUrl}}/Products?$select=ID,Name,Category/ID&$expand=Category
Accept: {{contentType}}

###
# @name selecting nested without expand => fails 400
GET {{baseUrl}}/Products?$select=ID,Name,Category/ID
Accept: {{contentType}}

###
# @name selecting deeply nested
GET {{baseUrl}}/Products(0)?$select=ID,Name,Category/Name,Category/Products/Name&$expand=Category/Products
Accept: {{contentType}}

###
# @name selecting deeply nested with individual expands
GET {{baseUrl}}/Products(0)?$select=ID,Name,Category/Name,Category/Products/Name&$expand=Category,Category/Products
Accept: {{contentType}}

###
# @name filter by price (decimal)
GET {{rootUrl}}/Products?$inlinecount=allpages&$filter=Price eq 22.8m
Accept: {{contentType}}


# --- Create Entity ---
###
# @name create new product
POST {{baseUrl}}/Products
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "ID": 998,
  "Description": "Test Description",
  "Name": "TestName",
  "Price": "12.88",
  "Rating": 1,
  "ReleaseDate": "2022-01-01T00:00:00"
}

###
# @name get new product
GET {{baseUrl}}/Products(998)
Accept: {{contentType}}

###
# @name merge new product
POST {{baseUrl}}/Products(998)
X-Http-Method: MERGE
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "Description": "Test Descriptioning!!!"
}

### PATCH  => 501
# @name update new product
PATCH {{baseUrl}}/Products(998)
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "Description": "Test Descriptioning!!!"
}
###
# @name update prop
PUT {{baseUrl}}/Products(998)/Description
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "Description": "Testing PropUpdate"
}

###
# @name update prop with raw value
PUT {{baseUrl}}/Products(998)/Description/$value
Content-Type: text/plain

Plain Text

###
# @name update prop with null
PUT {{baseUrl}}/Products(998)/Description
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "Description": null
}

###
# @name delete prop => 405
DELETE {{baseUrl}}/Products(998)/Description
Accept: {{contentType}}

###
# @name update category association
POST {{baseUrl}}/Products(999)
Accept: {{contentType}}
Content-Type: {{contentType}}
X-Http-Method: MERGE

{
  "Category": { uri: "{{baseUrl}}/Categories(1)" }
}


###
# @name delete new product
DELETE {{baseUrl}}/Products(998)
Accept: {{contentType}}

# --- Create Entity With Association ---
###
# @name create new product with association
POST {{baseUrl}}/Products
Accept: {{contentType}}
Content-Type: {{contentType}}

{
  "ID": 999,
  "Description": "Test Description",
  "Name": "TestName",
  "Price": "12.88",
  "Rating": 1,
  "ReleaseDate": "2022-01-01T00:00:00",
  "Category": { ID: 1 }
}
