name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    # Do not run on forks
    if: github.repository == 'odata2ts/odata2ts'
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - id: release
        uses: google-github-actions/release-please-action@v4.0.2
        with:
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout release PR
        # only if a PR has been created
        if: ${{ steps.release.outputs.pr }}
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJSON(steps.release.outputs.pr).headBranchName }}
          # Fetch the last 2 commits instead of just 1. (Fetching just 1 commit would overwrite the whole history)
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get last commit message
        id: last-commit
        # only if a PR has been created
        if: ${{ steps.release.outputs.pr }}
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT
      - name: Update yarn.lock in PR
        # only if a PR has been created
        if: ${{ steps.release.outputs.pr }}
        run: |
          yarn install --mode=update-lockfile
      - name: Commit changes
        # only if a PR has been created
        if: ${{ steps.release.outputs.pr }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: ${{ steps.last-commit.outputs.author }}
          commit_message: ${{ steps.last-commit.outputs.message }}
          commit_options: "--amend --no-edit"
          push_options: "--force"
          skip_fetch: true

  publish-npm:
    # publish only when released
    if: ${{ needs.release-please.outputs.releases_created == true || needs.release-please.outputs.releases_created == 'true' }}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install packages
        run: yarn --immutable
      - name: Build packages
        run: yarn build
      - name: Publish packages
        run: yarn workspaces foreach -A --topological-dev --no-private npm publish --tolerate-republish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.ODATA2TS_NPM_TOKEN }}
