import { ref } from "@odata2ts/odata-service";
import { describe, expect, test } from "vitest";
import { LIBRARY, LIBRARY_JSON_BATCH, UNKNOWN_ID } from "../LibraryTestConstants.js";

/**
 * `$batch` against the ASP.NET Core OData server - the one that, unlike the V2 server, speaks the **JSON**
 * wire format as well as multipart. The JSON shape goes through the dedicated JSON-batch client
 * (`LIBRARY_JSON_BATCH`, generated with `batch: { format: "json" }` and the one whose builder carries the
 * JSON wire format plus numeric `dependsOn`); the multipart shape goes through `LIBRARY`.
 */
describe("ASP.NET Library: $batch", () => {
  test("json answers every sub-request", async () => {
    const members = LIBRARY_JSON_BATCH.Members().query((b) => b.top(2));
    const count = LIBRARY_JSON_BATCH.Media().query((b) => b.count());

    const [membersResult, countResult] = await LIBRARY_JSON_BATCH.batch().add(members).add(count).execute();

    expect(membersResult.status).toBe(200);
    expect(membersResult.data?.value.length).toBe(2);

    expect(countResult.status).toBe(200);
    expect(countResult.data?.["@odata.count"]).toBeGreaterThan(0);
  });

  test("multipart answers every sub-request", async () => {
    const members = LIBRARY.Members().query((b) => b.top(2));

    const [membersResult] = await LIBRARY.batch().add(members).execute();

    expect(membersResult.status).toBe(200);
    expect(membersResult.data?.value.length).toBe(2);
  });

  test("continueOnError still answers the sub-request that follows a failing one", async () => {
    const missing = LIBRARY.Media(UNKNOWN_ID).query();
    const media = LIBRARY.Media().query((b) => b.top(1));

    const [missingResult, mediaResult] = await LIBRARY.batch()
      .add(missing)
      .add(media)
      .execute({ continueOnError: true });

    expect(missingResult.status).toBe(404);
    expect(mediaResult.status).toBe(200);
    expect(mediaResult.data?.value.length).toBe(1);
  });
});

/**
 * Request referencing, over the JSON wire format. A request that does not know the key of the entity it
 * addresses - because the key is generated by the very request it refers to - refers to that request by its
 * id: as a **body** reference (a navigation property bound through the `$<id>` token) or a **URL** reference
 * (a child request addressed under `$<id>`). The referencing request declares its ordering with the numeric
 * `dependsOn` (the parent's wire id).
 */
describe("ASP.NET Library: $batch referencing", () => {
  test("binds a child's navigation property to the just-created parent by body reference", async () => {
    const book = LIBRARY_JSON_BATCH.Media().asBookCollectionService().create({
      Title: "Referenced book",
      PageCount: 200,
      AgeRating: 1,
    });
    const copy = LIBRARY_JSON_BATCH.Copies().create({
      IsLoanable: true,
      Condition: 9,
      WeightKg: 1.2,
      InventoryNumber: 1001,
      Medium: { "@id": ref(1) },
    });

    const [bookResult, copyResult] = await LIBRARY_JSON_BATCH.batch()
      .add(book)
      .add(copy, { dependsOn: [1] })
      .execute();

    expect(bookResult.status).toBe(201);
    expect(copyResult.status).toBe(201);
  });

  test("creates a child under the just-created parent by URL reference", async () => {
    const audiobook = LIBRARY_JSON_BATCH.Media()
      .asAudiobookCollectionService()
      .create({ Title: "Referenced audiobook" });
    const chapter = LIBRARY_JSON_BATCH.Media()
      .asAudiobookCollectionService()
      .byRef(1)
      .Chapters()
      .create({ Title: "Referenced chapter" });

    const [audiobookResult, chapterResult] = await LIBRARY_JSON_BATCH.batch()
      .add(audiobook)
      .add(chapter, { dependsOn: [1] })
      .execute();

    expect(audiobookResult.status).toBe(201);
    expect(chapterResult.status).toBe(201);
  });

  test("surfaces the server's error for a request that references an id that does not exist", async () => {
    const orphan = LIBRARY_JSON_BATCH.Media()
      .asAudiobookCollectionService()
      .byRef(999)
      .Chapters()
      .create({ Title: "Orphan chapter" });

    const [orphanResult] = await LIBRARY_JSON_BATCH.batch().add(orphan).execute();

    expect(orphanResult.status).toBeGreaterThanOrEqual(400);
    expect(orphanResult.status).toBeLessThan(500);
  });
});
