import { ref } from "@odata2ts/odata-service";
import { describe, expect, test } from "vitest";
import { LIBRARY, LIBRARY_JSON_BATCH, UNKNOWN_ID } from "../LibraryTestConstants.js";

/**
 * `$batch` against the ASP.NET Core OData server - the one that, unlike the V2 server, speaks the **JSON**
 * wire format as well as multipart. The JSON shape goes through the dedicated JSON-batch client
 * (`LIBRARY_JSON_BATCH`, generated with `batch: { format: "json" }` and the one whose builder carries the
 * JSON wire format plus numeric `dependsOn`); the multipart shape goes through `LIBRARY`.
 */
describe("ASP.NET Library: $batch", () => {
  test("json answers every sub-request", async () => {
    const members = LIBRARY_JSON_BATCH.Members().query((b) => b.top(2));
    const count = LIBRARY_JSON_BATCH.Media().query((b) => b.count());

    const [membersResult, countResult] = await LIBRARY_JSON_BATCH.batch().add(members).add(count).execute();

    expect(membersResult.status).toBe(200);
    expect(membersResult.data?.value.length).toBe(2);

    expect(countResult.status).toBe(200);
    expect(countResult.data?.["@odata.count"]).toBeGreaterThan(0);
  });

  test("multipart answers every sub-request", async () => {
    const members = LIBRARY.Members().query((b) => b.top(2));

    const [membersResult] = await LIBRARY.batch().add(members).execute();

    expect(membersResult.status).toBe(200);
    expect(membersResult.data?.value.length).toBe(2);
  });

  test("continueOnError still answers the sub-request that follows a failing one", async () => {
    const missing = LIBRARY.Media(UNKNOWN_ID).query();
    const media = LIBRARY.Media().query((b) => b.top(1));

    const [missingResult, mediaResult] = await LIBRARY.batch()
      .add(missing)
      .add(media)
      .execute({ continueOnError: true });

    expect(missingResult.status).toBe(404);
    expect(mediaResult.status).toBe(200);
    expect(mediaResult.data?.value.length).toBe(1);
  });
});

/**
 * Request referencing, over the JSON wire format. A request that does not know the key of the entity it
 * addresses - because the key is generated by the very request it refers to - refers to that request by its
 * id: as a **body** reference (a navigation property bound through the `$<id>` token) or a **URL** reference
 * (a child request addressed under `$<id>`). The referencing request declares its ordering with the numeric
 * `dependsOn` (the parent's wire id).
 */
describe("ASP.NET Library: $batch referencing", () => {
  test("binds a child's navigation property to the just-created parent by body reference", async () => {
    const member = LIBRARY_JSON_BATCH.Members().create({ Name: "Referenced member", PreviousAddresses: [] });
    const loan = LIBRARY_JSON_BATCH.Loans().create({
      LoanedAt: "2026-01-01T10:00:00Z",
      DueDate: "2026-01-15",
      Member: { "@id": ref(1) },
    });

    const [memberResult, loanResult] = await LIBRARY_JSON_BATCH.batch()
      .add(member)
      .add(loan, { dependsOn: [1] })
      .execute();

    expect(memberResult.status).toBe(201);
    expect(loanResult.status).toBe(201);
  });

  test("creates a child under the just-created parent by URL reference", async () => {
    const member = LIBRARY_JSON_BATCH.Members().create({ Name: "Referenced member", PreviousAddresses: [] });
    const loan = LIBRARY_JSON_BATCH.Members().byRef(1).Loans().create({
      LoanedAt: "2026-01-01T10:00:00Z",
      DueDate: "2026-01-15",
    });

    const [memberResult, loanResult] = await LIBRARY_JSON_BATCH.batch()
      .add(member)
      .add(loan, { dependsOn: [1] })
      .execute();

    expect(memberResult.status).toBe(201);
    expect(loanResult.status).toBe(201);
  });

  test("fails the whole batch when a request references an id that does not exist", async () => {
    const orphan = LIBRARY_JSON_BATCH.Members().byRef(999).Loans().create({
      LoanedAt: "2026-01-01T10:00:00Z",
      DueDate: "2026-01-15",
    });

    // an unresolvable first-segment reference with no dependsOn fails the batch at parse time - the whole
    // envelope is a 500, so the client rejects rather than answering the slot
    await expect(LIBRARY_JSON_BATCH.batch().add(orphan).execute()).rejects.toMatchObject({ status: 500 });
  });
});
